name: Doryen-Build-Ubuntu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    name: Build (Ubuntu)
    runs-on: ${{ matrix.os }}
    # Set to true to allow a workflow run to pass when this job fails.
    # We purpose with this workflow is verify that Doryen compile on a wide variety of
    # operating systems and compiler, therefore it is necessary that the workflow does
    # not stop if any of these fails (it is the default behavior for the workflow to
    # stop on failure of one of these).
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        # This compilers are common to Ubuntu 16, Ubuntu 18 and Ubuntu 20.
        compiler: [
            gcc-7,
            gcc-8,
            gcc-9,
            clang-8,
            clang-9,
        ]
        # Add custom environment variables for verify the compilation with non-common compilers
        include:
          - os: ubuntu-16.04
            compiler: clang-6.0

          - os: ubuntu-18.04
            compiler: clang-6.0

          - os: ubuntu-18.04
            compiler: gcc-10

          - os: ubuntu-20.04
            compiler: clang-10

          - os: ubuntu-20.04
            compiler: gcc-10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Debug (Ubuntu)
        run: |
          sudo apt update
          sudo apt install libsdl1.2-dev
          mkdir cmake-build-debug
          cd cmake-build-debug
          cmake .. -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          make
