# This is a basic workflow to help you get started with Actions

name: Doryen-Ubuntu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name: [ubuntu-18.04-gcc-9]
  
        include:
          - name: ubuntu-18.04-gcc-9
            os: ubuntu-18.04
            compiler: gcc
            version: "9"
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install SDL 1.2.15
        run: sudo apt install libsdl1.2-dev

      - name: Create the Build Directory
        run: mkdir Build

      - name: Configure
        working-directory: ./Build
        run: cmake ..
      
      - name: Build
        working-directory: ./Build
        run: cmake --build . -j 2 --config ${{ matrix.config.config }}
      
      - name: Test
        working-directory: ./Build
        run: ctest -j 2
